import { readFileSync, writeFileSync } from "fs";

const extra = [
  ["yungsta", "Yungsta", ["Youngsta"], ["delhi"], "IN"],
  ["rebel-7", "Rebel 7", ["Rebel7"], ["delhi"], "IN"],
  ["100rbh", "100RBH", ["100 RBH", "sau rbh"], ["mumbai", "gully"], "IN"],
  ["kaam-bhaari", "Kaam Bhaari", ["KaamBhaari"], ["mumbai", "gully"], "IN"],
  ["spitfire", "Spitfire", ["Spitfire Mumbai"], ["mumbai", "gully"], "IN"],
  ["slowcheetah", "SlowCheetah", ["Slow Cheetah"], ["mumbai"], "IN"],
  ["gaush", "Gaush", ["Gaush Singh"], ["delhi"], "IN"],
  ["badshah", "Badshah", ["Aditya Prateek Singh Sisodia"], ["delhi"], "IN"],
  ["yo-yo-honey-singh", "Yo Yo Honey Singh", ["Honey Singh", "yoyo", "Yo Yo"], ["delhi"], "IN"],
  ["bohemia", "Bohemia", ["Raja Kumari no", "Punjabi Rap Star"], ["punjab"], "PK"],
  ["hiphop-tamizha", "Hiphop Tamizha", ["Hip Hop Tamizha", "Aadhi"], ["chennai", "tamil"], "IN"],
  ["arivu", "Arivu", ["Arivarasu Kalainesan"], ["chennai", "tamil"], "IN"],
  ["ofro", "ofRO", ["ofro"], ["chennai"], "IN"],
  ["vedan", "Vedan", [], ["kochi", "malayalam"], "IN"],
  ["dabzee", "Dabzee", ["Dabzee Mappila"], ["kochi", "malayalam"], "IN"],
  ["fejo", "Fejo", [], ["kochi", "malayalam"], "IN"],
  ["thirumali", "ThirumaLi", ["Thirumali"], ["kochi", "malayalam"], "IN"],
  ["street-academics", "Street Academics", ["SA"], ["kochi"], "IN"],
  ["mhr", "M.H.R", ["MHR", "M H R"], ["kochi"], "IN"],
  ["mc-heam", "MC Heam", ["Heam"], ["chennai"], "IN"],
  ["dopeadelicz", "Dopeadelicz", ["Dopeadelics"], ["chennai"], "IN"],
  ["big-deal", "Big Deal", ["BigDeal"], ["delhi"], "IN"],
  ["khasi-bloodz", "Khasi Bloodz", ["KhasiBloodz"], ["shillong", "northeast"], "IN"],
  ["moko-koza", "Moko Koza", ["Moko"], ["nagaland", "northeast"], "IN"],
  ["taj", "TAJ", ["Taj"], ["delhi"], "IN"],
  ["2facebleed", "2facebleed", ["2 Face Bleed", "twofacebleed"], ["delhi"], "IN"],
  ["bassick", "Bassick", [], ["delhi"], "IN"],
  ["mc-kode", "MC Kode", ["Kode"], ["mumbai"], "IN"],
  ["young-stunners", "Young Stunners", ["YS"], ["karachi"], "PK"],
  ["talha-anjum", "Talha Anjum", ["Anjum"], ["karachi"], "PK"],
  ["talhah-yunus", "Talhah Yunus", ["Yunus"], ["karachi"], "PK"],
  ["jokhay", "Jokhay", [], ["karachi"], "PK"],
  ["umair", "Umair", [], ["karachi"], "PK"],
  ["jj47", "JJ47", ["JJ 47"], ["karachi"], "PK"],
  ["shareh", "Shareh", [], ["karachi"], "PK"],
  ["rap-demon", "Rap Demon", ["RapDemon"], ["lahore"], "PK"],
  ["faris-shafi", "Faris Shafi", ["Faris"], ["islamabad"], "PK"],
  ["hard-kaur", "Hard Kaur", ["HardKaur"], ["uk-punjab"], "IN"],
  ["raja-kumari", "Raja Kumari", ["RajaKumari"], ["chennai"], "IN"],
  ["ahmer", "Ahmer", ["Ahmer Javed"], ["srinagar", "kashmir"], "IN"],
  ["nanku", "Nanku", [], ["lucknow"], "IN"],
  ["baghira", "BAGHIRA", ["Baghira"], ["delhi"], "IN"],
  ["crook", "Crook", ["KR$NA Crook no"], ["delhi"], "IN"],
  ["edge", "Edge", [], ["delhi"], "IN"],
  ["superzero", "Superzero", ["Super Zero"], ["mumbai"], "IN"],
  ["mellow-d", "Mellow D", ["MellowD"], ["mumbai"], "IN"],
  ["vanjre", "Vanjre", [], ["pune"], "IN"],
  ["shauharty", "Shauharty", ["Shauharty Beats"], ["delhi"], "IN"],
  ["ricky-nimje", "Ricky Nimje", ["RickyNimje"], ["nagpur"], "IN"],
  ["gurbax", "Gurbax", [], ["punjab"], "IN"],
  ["epr", "EPR", ["Eyeless Production"], ["bengaluru"], "IN"],
  ["mahan", "Mahan", ["Mahan Rahja"], ["bengaluru"], "IN"],
  ["slia", "SLIA", [], ["delhi"], "IN"],
  ["wolf", "WOLF", ["Wolf"], ["delhi"], "IN"],
  ["dakait", "Dakait", [], ["delhi"], "IN"],
  ["aniket-rana", "Aniket Rana", ["Aniket"], ["delhi"], "IN"],
  ["yung-blaze", "Yung Blaze", ["Young Blaze"], ["mumbai"], "IN"],
  ["mc-laltain", "MC Laltain", ["Laltain"], ["kolkata"], "IN"],
  ["mc-headshot", "MC Headshot", ["Headshot"], ["kolkata"], "IN"],
  ["enlive", "Enlive", [], ["kolkata"], "IN"],
  ["dhanji", "Dhanji", [], ["ahmedabad"], "IN"],
  ["bhaskar-already-skip", "skip", [], [], "IN"],
  ["rawal-already-skip", "skip", [], [], "IN"],
  ["krsna-already-skip", "skip", [], [], "IN"],
  ["mc-insane", "MC Insane", ["Insane"], ["delhi"], "IN"],
  ["raftaar-skip", "skip", [], [], "IN"],
  ["ikka-skip", "skip", [], [], "IN"],
  ["emiway-skip", "skip", [], [], "IN"],
  ["stan-skip", "skip", [], [], "IN"],
  ["divine-skip", "skip", [], [], "IN"],
  ["naezy-skip", "skip", [], [], "IN"],
  ["king-skip", "skip", [], [], "IN"],
  ["paradox-skip", "skip", [], [], "IN"],
  ["hanumankind-skip", "skip", [], [], "IN"],
  ["panther-skip", "skip", [], [], "IN"],
  ["raga-skip", "skip", [], [], "IN"],
  ["karma-skip", "skip", [], [], "IN"],
  ["bella-skip", "skip", [], [], "IN"],
  ["qaab-skip", "skip", [], [], "IN"],
  ["loka-skip", "skip", [], [], "IN"],
  ["yashraj-skip", "skip", [], [], "IN"],
  ["frappe-skip", "skip", [], [], "IN"],
  ["bharg-skip", "skip", [], [], "IN"],
  ["fotty-skip", "skip", [], [], "IN"],
  ["dino-skip", "skip", [], [], "IN"],
  ["brodha-v-skip", "skip", [], [], "IN"],
  ["prabh-skip", "skip", [], [], "IN"],
  ["ikka2", "Ikka", ["Ikkaworld"], ["delhi"], "IN"],
  ["gully-gang", "Gully Gang", ["GullyGang"], ["mumbai"], "IN"],
  ["azadi-records", "Azadi Records", ["Azadi"], ["delhi"], "IN"],
  ["masss", "Masss", ["MASS"], ["delhi"], "IN"],
  ["blckk", "BLCKK", ["Blackk"], ["delhi"], "IN"],
  ["zahir", "Zahir", [], ["delhi"], "IN"],
  ["aflo", "AFLO", [], ["delhi"], "IN"],
  ["yashraj-mukhate", "Yashraj Mukhate", ["Mukhate"], ["indore"], "IN"],
  ["seedhe-skip", "skip", [], [], "IN"],
  ["calm-skip", "skip", [], [], "IN"],
  ["encore-skip", "skip", [], [], "IN"],
  ["mc-altaf-skip", "skip", [], [], "IN"],
  ["seven-bantai-skip", "skip", [], [], "IN"],
  ["shah-rule-skip", "skip", [], [], "IN"],
  ["sez-on-the-beat", "Sez on the Beat", ["SezOnTheBeat", "Sez"], ["delhi"], "IN"],
  ["karan-aujla", "Karan Aujla", ["Aujla"], ["punjab"], "IN"],
  ["sidhu-moose-wala", "Sidhu Moose Wala", ["Moose Wala", "SMW"], ["punjab"], "IN"],
  ["shubh", "Shubh", [], ["punjab"], "IN"],
  ["ap-dhillon", "AP Dhillon", ["APDhillon"], ["punjab"], "IN"],
  ["gurinder-gill", "Gurinder Gill", ["GMINDR"], ["punjab"], "IN"],
  ["intense", "Intense", [], ["punjab"], "IN"],
  ["sanjay-c", "Sanjay C", ["SanjayC"], ["delhi"], "IN"],
  ["raftaar-already", "skip", [], [], "IN"],
  ["deep-money", "Deep Money", ["DeepMoney"], ["punjab"], "IN"],
  ["imran-khan", "Imran Khan", ["Amplifier"], ["punjab"], "PK"],
  ["gully-boy-cast", "Gully Boy Cast", [], ["mumbai"], "IN"],
  ["slowcheeta", "skip", [], [], "IN"],
  ["mc-lophole", "MC Lophole", ["Lophole"], ["mumbai"], "IN"],
  ["7bantai", "skip", [], [], "IN"],
  ["d-major", "D'Evil", ["D Evil", "Devil Mumbai"], ["mumbai"], "IN"],
  ["eka", "EKA", ["Eka"], ["mumbai"], "IN"],
  ["mafatlal", "Mafatlal", [], ["mumbai"], "IN"],
  ["bombay-bantai", "Bombay Bantai", [], ["mumbai"], "IN"],
  ["ghaits", "GHAITS", [], ["delhi"], "IN"],
  ["khullar-gan", "Khullar G", ["KhullarG"], ["delhi"], "IN"],
  ["raftaar-ikka", "skip", [], [], "IN"],
  ["naezy-divine", "skip", [], [], "IN"],
  ["seedhe-maut-skip", "skip", [], [], "IN"],
  ["mc-wale", "MC Wale", [], ["hyderabad"], "IN"],
  ["rebel-kid", "Rebel Kid", ["RebelKid"], ["delhi"], "IN"],
  ["dgimmick", "DGimmick", ["D Gimmick"], ["delhi"], "IN"],
  ["flow-art", "FlowArt", ["Flow Art"], ["delhi"], "IN"],
  ["yashraj-already", "skip", [], [], "IN"],
  ["panther-already", "skip", [], [], "IN"],
  ["hanumankind-already", "skip", [], [], "IN"],
  ["mc-square", "MC Square", ["MCSquare"], ["haryana"], "IN"],
  ["thorns", "Thorns", [], ["delhi"], "IN"],
  ["zahir-already", "skip", [], [], "IN"],
];

const file = new URL("../catalogue/seed.json", import.meta.url);
const seed = JSON.parse(readFileSync(file, "utf8"));
const have = new Set(seed.artists.map((a) => a.id));
const haveName = new Set(
  seed.artists.flatMap((a) => [a.name, a.id, ...(a.aliases ?? [])].map((x) => String(x).toLowerCase())),
);

let added = 0;
for (const [id, name, aliases, sceneTags, country] of extra) {
  if (name === "skip") continue;
  const names = [id, name, ...aliases].map((x) => String(x).toLowerCase());
  if (names.some((n) => have.has(n) || haveName.has(n))) continue;
  seed.artists.push({
    id,
    name,
    aliases,
    sceneTags,
    country,
    active: true,
  });
  have.add(id);
  haveName.add(name.toLowerCase());
  added += 1;
}

writeFileSync(file, JSON.stringify(seed, null, 2) + "\n");
console.log("added", added, "total artists", seed.artists.length, "tracks", seed.tracks.length);
