import type { Artist, Track } from "../types";
import { normalizeText } from "../normalize";

function artist(
  id: string,
  name: string,
  aliases: string[],
  tags: string[] = [],
): Artist {
  return {
    id,
    name,
    normalizedName: normalizeText(name),
    aliases,
    country: "IN",
    sceneTags: tags,
    active: true,
  };
}

export const ARTISTS: Artist[] = [
  artist("seedhe-maut", "Seedhe Maut", ["SM", "SeedheMaut", "seedhe maut", "Encore x Calm"], ["delhi"]),
  artist("encore-abj", "Encore ABJ", ["Encore", "ABJ"], ["delhi", "seedhe-maut"]),
  artist("calm", "Calm", ["Calm Seedhe Maut"], ["delhi", "seedhe-maut"]),
  artist("krsna", "KR$NA", ["KRSNA", "KrSna", "Krsna", "Youngest In Charge"], ["delhi", "kalamkaar"]),
  artist("mc-stan", "MC Stan", ["Stan", "MCSTAN", "MC ST∆N"], ["pune"]),
  artist("divine", "DIVINE", ["Divine", "Vivian Fernandes"], ["mumbai", "gully"]),
  artist("naezy", "Naezy", ["Naezy Naved", "Naved Shaikh"], ["mumbai", "gully"]),
  artist("raftaar", "Raftaar", ["Raftar"], ["delhi"]),
  artist("emiway", "Emiway Bantai", ["Emiway", "Bantai"], ["mumbai"]),
  artist("prabh-deep", "Prabh Deep", ["Prabhdeep", "Prabh"], ["delhi"]),
  artist("brodha-v", "Brodha V", ["BrodhaV", "Broda V"], ["bengaluru"]),
  artist("dino-james", "Dino James", ["Dino"], ["bhopal"]),
  artist("ikka", "Ikka", ["Ikka Singh"], ["delhi"]),
  artist("fotty-seven", "Fotty Seven", ["Fotty7", "47"], ["delhi"]),
  artist("yashraj", "Yashraj", ["Yash Raj"], ["delhi"]),
  artist("frappe-ash", "Frappe Ash", ["Frappe"], ["delhi"]),
  artist("bharg", "Bharg", [], ["delhi"]),
  artist("rawal", "Rawal", [], ["delhi"]),
  artist("bhaskar", "Bhaskar", [], ["delhi"]),
  artist("karma", "Karma", [], ["delhi"]),
  artist("king", "King", ["King MC"], ["delhi"]),
  artist("hanumankind", "Hanumankind", ["Sooraj Cherukat"], ["kochi"]),
];

function ref(id: string, role: "primary" | "feature" | "group" = "primary") {
  const found = ARTISTS.find((a) => a.id === id);
  if (!found) throw new Error(`Missing artist ${id}`);
  return { id, name: found.name, role };
}

function track(
  partial: Omit<Track, "normalizedTitle" | "country" | "genre" | "artists"> & {
    artists: Track["artists"];
  },
): Track {
  return {
    ...partial,
    normalizedTitle: normalizeText(partial.title),
    country: "IN",
    genre: "DHH",
  };
}

export const TRACKS: Track[] = [
  track({
    id: "namastute",
    title: "Namastute",
    artists: [ref("seedhe-maut", "group")],
    primaryArtistId: "seedhe-maut",
    aliases: ["namastute", "namaste"],
    album: "Nayaab",
    releaseYear: 2021,
    youtubeVideoId: "YuWUJg3Kdks",
    youtubeStartFaithful: true,
    sourcePlaylists: ["ytm-dhh-1", "jiosaavn-dhh"],
    sceneTags: ["delhi", "azadi"],
    difficulty: 2,
    active: true,
    introQuality: "faithful",
  }),
  track({
    id: "nanchaku",
    title: "Nanchaku",
    artists: [ref("seedhe-maut", "group"), ref("mc-stan", "feature")],
    primaryArtistId: "seedhe-maut",
    aliases: ["nunchaku", "nanchku"],
    releaseYear: 2021,
    sourcePlaylists: ["ytm-dhh-1", "jiosaavn-dhh"],
    sceneTags: ["delhi", "pune"],
    difficulty: 2,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "khatta-flow",
    title: "Khatta Flow",
    artists: [ref("seedhe-maut", "group"), ref("krsna", "feature")],
    primaryArtistId: "seedhe-maut",
    aliases: ["khattaflow", "khata flow"],
    album: "Lunch Break",
    releaseYear: 2023,
    sourcePlaylists: ["ytm-dhh-1", "jiosaavn-dhh"],
    sceneTags: ["delhi"],
    difficulty: 2,
    active: true,
    introQuality: "unusable",
  }),
  track({
    id: "kohra",
    title: "Kohra",
    artists: [ref("seedhe-maut", "group")],
    primaryArtistId: "seedhe-maut",
    aliases: ["kohraa", "khora"],
    album: "Lunch Break",
    releaseYear: 2023,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["delhi"],
    difficulty: 3,
    active: true,
    introQuality: "unusable",
  }),
  track({
    id: "101",
    title: "101",
    artists: [ref("seedhe-maut", "group")],
    primaryArtistId: "seedhe-maut",
    aliases: ["one oh one", "one zero one"],
    releaseYear: 2019,
    youtubeVideoId: "IUFPs3j341k",
    youtubeStartFaithful: true,
    sourcePlaylists: ["ytm-dhh-1"],
    sceneTags: ["delhi", "azadi"],
    difficulty: 3,
    active: true,
    introQuality: "faithful",
  }),
  track({
    id: "shaktimaan",
    title: "Shaktimaan",
    artists: [ref("seedhe-maut", "group")],
    primaryArtistId: "seedhe-maut",
    aliases: ["shaktiman"],
    album: "Lunch Break",
    releaseYear: 2023,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["delhi"],
    difficulty: 3,
    active: true,
    introQuality: "unusable",
  }),
  track({
    id: "11k",
    title: "11K",
    artists: [ref("seedhe-maut", "group")],
    primaryArtistId: "seedhe-maut",
    aliases: ["11 k", "eleven k"],
    releaseYear: 2022,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["delhi"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "no-cap",
    title: "No Cap",
    artists: [ref("krsna")],
    primaryArtistId: "krsna",
    aliases: ["nocap"],
    releaseYear: 2021,
    youtubeVideoId: "PejQbGZraqg",
    youtubeStartFaithful: true,
    sourcePlaylists: ["ytm-dhh-1", "jiosaavn-dhh"],
    sceneTags: ["delhi", "kalamkaar"],
    difficulty: 2,
    active: true,
    introQuality: "faithful",
  }),
  track({
    id: "saza-e-maut",
    title: "Saza-E-Maut",
    artists: [ref("krsna"), ref("raftaar", "feature")],
    primaryArtistId: "krsna",
    aliases: ["saza e maut", "sazaemaut", "saza"],
    releaseYear: 2020,
    sourcePlaylists: ["ytm-dhh-1"],
    sceneTags: ["delhi"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "joota-japani",
    title: "Joota Japani",
    artists: [ref("krsna")],
    primaryArtistId: "krsna",
    aliases: ["juta japani", "jootajapani"],
    releaseYear: 2022,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["delhi"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "mere-gully-mein",
    title: "Mere Gully Mein",
    artists: [ref("divine"), ref("naezy", "feature")],
    primaryArtistId: "divine",
    aliases: ["mere gali mein", "meregullymein", "meri gully mein"],
    releaseYear: 2015,
    youtubeVideoId: "1bK5dzwhu-I",
    youtubeStartFaithful: true,
    sourcePlaylists: ["jiosaavn-dhh", "ytm-dhh-1"],
    sceneTags: ["mumbai", "gully"],
    difficulty: 1,
    active: true,
    introQuality: "faithful",
  }),
  track({
    id: "farak",
    title: "Farak",
    artists: [ref("divine")],
    primaryArtistId: "divine",
    aliases: ["farq", "fark"],
    album: "Kohinoor",
    releaseYear: 2019,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["mumbai"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "359-am",
    title: "3:59 AM",
    artists: [ref("divine")],
    primaryArtistId: "divine",
    aliases: ["359 am", "three fifty nine", "3 59"],
    releaseYear: 2018,
    sourcePlaylists: ["ytm-dhh-1"],
    sceneTags: ["mumbai"],
    difficulty: 2,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "jungli-sher",
    title: "Jungli Sher",
    artists: [ref("divine")],
    primaryArtistId: "divine",
    aliases: ["junglee sher", "jungle sher"],
    releaseYear: 2016,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["mumbai"],
    difficulty: 2,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "basti-ka-hasti",
    title: "Basti Ka Hasti",
    artists: [ref("mc-stan")],
    primaryArtistId: "mc-stan",
    aliases: ["basti ka hasti", "bastikahasti"],
    album: "Insaan",
    releaseYear: 2022,
    sourcePlaylists: ["jiosaavn-dhh", "ytm-dhh-1"],
    sceneTags: ["pune"],
    difficulty: 2,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "insaan",
    title: "Insaan",
    artists: [ref("mc-stan")],
    primaryArtistId: "mc-stan",
    aliases: ["insan"],
    album: "Insaan",
    releaseYear: 2022,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["pune"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "gunehgar",
    title: "Gunehgar",
    artists: [ref("mc-stan")],
    primaryArtistId: "mc-stan",
    aliases: ["gunhegar", "gunehgaar"],
    releaseYear: 2021,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["pune"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "machayenge",
    title: "Machayenge",
    artists: [ref("emiway")],
    primaryArtistId: "emiway",
    aliases: ["machayenge 1", "machayenge original"],
    releaseYear: 2018,
    sourcePlaylists: ["ytm-dhh-1"],
    sceneTags: ["mumbai"],
    difficulty: 1,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "company",
    title: "Company",
    artists: [ref("emiway")],
    primaryArtistId: "emiway",
    aliases: ["compeny"],
    releaseYear: 2022,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["mumbai"],
    difficulty: 2,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "aathma-rama",
    title: "Aathma Rama",
    artists: [ref("brodha-v")],
    primaryArtistId: "brodha-v",
    aliases: ["atma rama", "aathmarama"],
    releaseYear: 2017,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["bengaluru"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "class-sikh",
    title: "Class-Sikh",
    artists: [ref("prabh-deep")],
    primaryArtistId: "prabh-deep",
    aliases: ["classsikh", "class sikh"],
    album: "Class-Sikh",
    releaseYear: 2017,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["delhi"],
    difficulty: 4,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "haan",
    title: "Haan",
    artists: [ref("dino-james")],
    primaryArtistId: "dino-james",
    aliases: ["han"],
    releaseYear: 2018,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["bhopal"],
    difficulty: 2,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "sheikh-chilli",
    title: "Sheikh Chilli",
    artists: [ref("raftaar")],
    primaryArtistId: "raftaar",
    aliases: ["sheikh chili", "sheikhchilli"],
    releaseYear: 2018,
    sourcePlaylists: ["ytm-dhh-1"],
    sceneTags: ["delhi"],
    difficulty: 3,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "khatam",
    title: "Khatam",
    artists: [ref("ikka")],
    primaryArtistId: "ikka",
    aliases: ["khtm"],
    releaseYear: 2020,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["delhi"],
    difficulty: 4,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "big-dawgs",
    title: "Big Dawgs",
    artists: [ref("hanumankind")],
    primaryArtistId: "hanumankind",
    aliases: ["big dogs", "bigdawgs"],
    releaseYear: 2024,
    sourcePlaylists: ["ytm-dhh-1"],
    sceneTags: ["kochi"],
    difficulty: 1,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "yashraj-keh-diya",
    title: "Keh Diya",
    artists: [ref("yashraj")],
    primaryArtistId: "yashraj",
    aliases: ["kehdiya"],
    releaseYear: 2022,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["delhi"],
    difficulty: 4,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "frappe-no-days-off",
    title: "No Days Off",
    artists: [ref("frappe-ash")],
    primaryArtistId: "frappe-ash",
    aliases: ["nodaysoff"],
    releaseYear: 2023,
    sourcePlaylists: ["ytm-dhh-2"],
    sceneTags: ["delhi"],
    difficulty: 4,
    active: true,
    introQuality: "uncertain",
  }),
  track({
    id: "rawal-khatta",
    title: "DHH Anthem",
    artists: [ref("rawal"), ref("bhaskar", "feature")],
    primaryArtistId: "rawal",
    aliases: ["dhh anthem"],
    releaseYear: 2021,
    sourcePlaylists: ["jiosaavn-dhh"],
    sceneTags: ["delhi"],
    difficulty: 5,
    active: false,
    introQuality: "unusable",
  }),
];

export const PLAYLIST_SOURCES = [
  {
    id: "jiosaavn-dhh",
    name: "JioSaavn Desi Hip-Hop",
    kind: "metadata",
    note: "Curation reference only. Does not imply a legal playable stream.",
  },
  {
    id: "ytm-dhh-1",
    name: "YouTube Music Desi Hip-Hop",
    kind: "metadata",
    note: "Curation reference only.",
  },
  {
    id: "ytm-dhh-2",
    name: "YouTube Music Desi Hip-Hop (alt)",
    kind: "metadata",
    note: "Curation reference only.",
  },
];
